name: releaseDeckAllInOne
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACK_NAME: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0
          cache: pip
          architecture: x64
      - name: Setup Python Package
        run: |
          cd ./script/
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -U cos-python-sdk-v5
          cd ..
      - name: Run releaseDeck.py
        run: |
          cd ./script/
          python releaseDeck.py
          cd ..
      - name: Run uploadDeckResourceCos.py
        run: |
          cd ./script/
          python uploadDeckResourceCos.py ${{ secrets.EXTIVERSECOSSECRETID }} ${{ secrets.EXTIVERSECOSSECRETKEY }}
          cd ..
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./target/deck/index.json
      - name: Commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: '.'
          author_name: Github CI
          message: '[Bot] 刷新源数据'
          push: true
          # remove: './deck/index.json'
          # tag_push: '--force'
